// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cc.jifen.portal;

import cc.jifen.portal.Goods;
import cc.jifen.portal.GoodsDataOnDemand;
import cc.jifen.portal.GoodsIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect GoodsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: GoodsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: GoodsIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: GoodsIntegrationTest: @Transactional;
    
    @Autowired
    private GoodsDataOnDemand GoodsIntegrationTest.dod;
    
    @Test
    public void GoodsIntegrationTest.testCountGoodses() {
        Assert.assertNotNull("Data on demand for 'Goods' failed to initialize correctly", dod.getRandomGoods());
        long count = Goods.countGoodses();
        Assert.assertTrue("Counter for 'Goods' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void GoodsIntegrationTest.testFindGoods() {
        Goods obj = dod.getRandomGoods();
        Assert.assertNotNull("Data on demand for 'Goods' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Goods' failed to provide an identifier", id);
        obj = Goods.findGoods(id);
        Assert.assertNotNull("Find method for 'Goods' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Goods' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void GoodsIntegrationTest.testFindAllGoodses() {
        Assert.assertNotNull("Data on demand for 'Goods' failed to initialize correctly", dod.getRandomGoods());
        long count = Goods.countGoodses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Goods', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Goods> result = Goods.findAllGoodses();
        Assert.assertNotNull("Find all method for 'Goods' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Goods' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void GoodsIntegrationTest.testFindGoodsEntries() {
        Assert.assertNotNull("Data on demand for 'Goods' failed to initialize correctly", dod.getRandomGoods());
        long count = Goods.countGoodses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Goods> result = Goods.findGoodsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Goods' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Goods' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void GoodsIntegrationTest.testFlush() {
        Goods obj = dod.getRandomGoods();
        Assert.assertNotNull("Data on demand for 'Goods' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Goods' failed to provide an identifier", id);
        obj = Goods.findGoods(id);
        Assert.assertNotNull("Find method for 'Goods' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyGoods(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Goods' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GoodsIntegrationTest.testMergeUpdate() {
        Goods obj = dod.getRandomGoods();
        Assert.assertNotNull("Data on demand for 'Goods' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Goods' failed to provide an identifier", id);
        obj = Goods.findGoods(id);
        boolean modified =  dod.modifyGoods(obj);
        Integer currentVersion = obj.getVersion();
        Goods merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Goods' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GoodsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Goods' failed to initialize correctly", dod.getRandomGoods());
        Goods obj = dod.getNewTransientGoods(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Goods' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Goods' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Goods' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void GoodsIntegrationTest.testRemove() {
        Goods obj = dod.getRandomGoods();
        Assert.assertNotNull("Data on demand for 'Goods' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Goods' failed to provide an identifier", id);
        obj = Goods.findGoods(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Goods' with identifier '" + id + "'", Goods.findGoods(id));
    }
    
}
