// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cc.jifen.portal;

import cc.jifen.portal.GoodsCategory;
import cc.jifen.portal.GoodsCategoryDataOnDemand;
import cc.jifen.portal.GoodsCategoryIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect GoodsCategoryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: GoodsCategoryIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: GoodsCategoryIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: GoodsCategoryIntegrationTest: @Transactional;
    
    @Autowired
    private GoodsCategoryDataOnDemand GoodsCategoryIntegrationTest.dod;
    
    @Test
    public void GoodsCategoryIntegrationTest.testCountGoodsCategorys() {
        Assert.assertNotNull("Data on demand for 'GoodsCategory' failed to initialize correctly", dod.getRandomGoodsCategory());
        long count = GoodsCategory.countGoodsCategorys();
        Assert.assertTrue("Counter for 'GoodsCategory' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void GoodsCategoryIntegrationTest.testFindGoodsCategory() {
        GoodsCategory obj = dod.getRandomGoodsCategory();
        Assert.assertNotNull("Data on demand for 'GoodsCategory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GoodsCategory' failed to provide an identifier", id);
        obj = GoodsCategory.findGoodsCategory(id);
        Assert.assertNotNull("Find method for 'GoodsCategory' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'GoodsCategory' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void GoodsCategoryIntegrationTest.testFindAllGoodsCategorys() {
        Assert.assertNotNull("Data on demand for 'GoodsCategory' failed to initialize correctly", dod.getRandomGoodsCategory());
        long count = GoodsCategory.countGoodsCategorys();
        Assert.assertTrue("Too expensive to perform a find all test for 'GoodsCategory', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<GoodsCategory> result = GoodsCategory.findAllGoodsCategorys();
        Assert.assertNotNull("Find all method for 'GoodsCategory' illegally returned null", result);
        Assert.assertTrue("Find all method for 'GoodsCategory' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void GoodsCategoryIntegrationTest.testFindGoodsCategoryEntries() {
        Assert.assertNotNull("Data on demand for 'GoodsCategory' failed to initialize correctly", dod.getRandomGoodsCategory());
        long count = GoodsCategory.countGoodsCategorys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<GoodsCategory> result = GoodsCategory.findGoodsCategoryEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'GoodsCategory' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'GoodsCategory' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void GoodsCategoryIntegrationTest.testFlush() {
        GoodsCategory obj = dod.getRandomGoodsCategory();
        Assert.assertNotNull("Data on demand for 'GoodsCategory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GoodsCategory' failed to provide an identifier", id);
        obj = GoodsCategory.findGoodsCategory(id);
        Assert.assertNotNull("Find method for 'GoodsCategory' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyGoodsCategory(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'GoodsCategory' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GoodsCategoryIntegrationTest.testMergeUpdate() {
        GoodsCategory obj = dod.getRandomGoodsCategory();
        Assert.assertNotNull("Data on demand for 'GoodsCategory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GoodsCategory' failed to provide an identifier", id);
        obj = GoodsCategory.findGoodsCategory(id);
        boolean modified =  dod.modifyGoodsCategory(obj);
        Integer currentVersion = obj.getVersion();
        GoodsCategory merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'GoodsCategory' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GoodsCategoryIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'GoodsCategory' failed to initialize correctly", dod.getRandomGoodsCategory());
        GoodsCategory obj = dod.getNewTransientGoodsCategory(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'GoodsCategory' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'GoodsCategory' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'GoodsCategory' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void GoodsCategoryIntegrationTest.testRemove() {
        GoodsCategory obj = dod.getRandomGoodsCategory();
        Assert.assertNotNull("Data on demand for 'GoodsCategory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GoodsCategory' failed to provide an identifier", id);
        obj = GoodsCategory.findGoodsCategory(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'GoodsCategory' with identifier '" + id + "'", GoodsCategory.findGoodsCategory(id));
    }
    
}
