// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cc.jifen.portal;

import cc.jifen.portal.GoodsCategoryDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect GoodsCategoryDataOnDemand_Roo_Configurable {
    
    declare @type: GoodsCategoryDataOnDemand: @Configurable;
    
}
